// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZfoTT4GIbPG23YoxdzqCToWvbkizyMo',
    appId: '1:1050206498085:web:e5429b358d4a9e1722fecc',
    messagingSenderId: '1050206498085',
    projectId: 'matheal-ef41a',
    authDomain: 'matheal-ef41a.firebaseapp.com',
    storageBucket: 'matheal-ef41a.firebasestorage.app',
    measurementId: 'G-5G248G32DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASb2Yr01YALwTNYo0OZgpLSunlXFqTgUk',
    appId: '1:1050206498085:android:041ab1b2b870520822fecc',
    messagingSenderId: '1050206498085',
    projectId: 'matheal-ef41a',
    storageBucket: 'matheal-ef41a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZzsZ-Q7YLLWAGJJifrHk2YUAciMczs18',
    appId: '1:1050206498085:ios:9083faa110bc982422fecc',
    messagingSenderId: '1050206498085',
    projectId: 'matheal-ef41a',
    storageBucket: 'matheal-ef41a.firebasestorage.app',
    iosClientId: '1050206498085-3l4jhb62donlrrqqcfuvtrnajngjhdk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.matheal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZzsZ-Q7YLLWAGJJifrHk2YUAciMczs18',
    appId: '1:1050206498085:ios:9083faa110bc982422fecc',
    messagingSenderId: '1050206498085',
    projectId: 'matheal-ef41a',
    storageBucket: 'matheal-ef41a.firebasestorage.app',
    iosClientId: '1050206498085-3l4jhb62donlrrqqcfuvtrnajngjhdk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.matheal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtZfoTT4GIbPG23YoxdzqCToWvbkizyMo',
    appId: '1:1050206498085:web:fa576539d07f0c1d22fecc',
    messagingSenderId: '1050206498085',
    projectId: 'matheal-ef41a',
    authDomain: 'matheal-ef41a.firebaseapp.com',
    storageBucket: 'matheal-ef41a.firebasestorage.app',
    measurementId: 'G-3WV487NFKR',
  );

}