name: matheal
description: A Flutter app for maternal health care

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_markdown: ^0.6.18

  google_fonts: ^5.0.0
  flutter_svg: ^2.0.7
  
  # State Management
  provider: ^6.1.2

  
  # Firebase
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.3
  firebase_core: ^3.15.2
  firebase_storage: ^12.3.4

  firebase_app_check: ^0.3.2+10

  # Storage & Utilities
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  
  # Notifications & Local Storage
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  intl: ^0.18.1 # Or the latest version
  just_audio: ^0.9.36 # Or the latest version


  
  # Media & Auth
  image_picker: ^1.0.7
  url_launcher: ^6.3.0


  local_auth: ^2.1.5
  
  # Network
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  glass_kit: ^4.0.1
  share_plus: ^7.2.2 
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  fl_chart: ^1.1.1
  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-VariableFont_wght.ttf
    - family: Bricolage_Grotesque
      fonts:
        - asset: assets/fonts/BricolageGrotesque-VariableFont_opsz,wdth,wght.ttf
        - asset: assets/fonts/BricolageGrotesque-Medium.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf



  
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/onboarding/
    - assets/fonts/