name: matheal
description: A Flutter app for maternal health care

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.7
  
  # State Management
  provider: ^6.1.2

  
  # Firebase
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.3
  firebase_core: ^3.15.2
  firebase_storage: ^12.3.4

  firebase_app_check: ^0.3.2+10

  # Storage & Utilities
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  
  # Notifications & Local Storage
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  intl: ^0.18.1 # Or the latest version
  just_audio: ^0.9.36 # Or the latest version

  
  # Media & Auth
  image_picker: ^0.8.7
  url_launcher: ^6.3.0

  local_auth: ^2.1.5
  
  # Network
  http: ^1.2.2
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/onboarding/onboarding1.png
    - assets/onboarding/onboarding2.png
    - assets/onboarding/onboarding3.png
    - assets/onboarding/onboarding4.png